export const GET_VAPESHOPS = 'VAPESHOPS_GET_ALL';
export const GET_ONE_VAPESHOP = 'VAPESHOPS_GET_ONE';
export const OPEN_AUTHENTICATION_MODAL = 'OPEN_AUTHENTICATION_MODAL';
export const CLOSE_AUTHENTICATION_MODAL = 'CLOSE_AUTHENTICATION_MODAL';
