export const ADD_ACTIVE_MARKER = 'ADD_ACTIVE_MARKER';
export const REMOVE_ACTIVE_MARKER = 'REMOVE_ACTIVE_MARKER';
export const SHOW_INFOWINDOW = 'SHOW_INFOWINDOW';
export const HIDE_INFOWINDOW = 'HIDE_INFOWINDOW';