export const OPEN_AUTHENTICATION_MODAL = 'OPEN_AUTHENTICATION_MODAL';
export const CLOSE_AUTHENTICATION_MODAL = 'CLOSE_AUTHENTICATION_MODAL';
export const SHOW_REGISTRATION_MODAL = 'SHOW_REGISTRATION_MODAL';
export const SHOW_AUTHENTICATION_MODAL = 'SHOW_AUTHENTICATION_MODAL';

export const OPEN_NEW_VAPESHOP_MODAL = 'OPEN_NEW_VAPESHOP_MODAL';
export const CLOSE_NEW_VAPESHOP_MODAL = 'CLOSE_NEW_VAPESHOP_MODAL';
export const CREATE_VAPESHOP = 'CREATE_VAPESHOP';

export const EDIT_VAPESHOP = 'EDIT_VAPESHOP';
export const OPEN_EDIT_VAPESHOP_MODAL = 'OPEN_EDIT_VAPESHOP_MODAL';
export const CLOSE_EDIT_VAPESHOP_MODAL = 'CLOSE_EDIT_VAPESHOP_MODAL';
