export const OPEN_AUTHENTICATION_MODAL = 'OPEN_AUTHENTICATION_MODAL';
export const CLOSE_AUTHENTICATION_MODAL = 'CLOSE_AUTHENTICATION_MODAL';
export const SHOW_REGISTRATION_MODAL = 'SHOW_REGISTRATION_MODAL';
export const SHOW_AUTHENTICATION_MODAL = 'SHOW_AUTHENTICATION_MODAL';
