export const ADD_VAPESHOPS = 'ADD_VAPESHOPS';
export const ADD_VAPESHOP = 'ADD_VAPESHOP';
export const CLEAR_ACTIVE_VAPESHOP = 'CLEAR_ACTIVE_VAPESHOP';
export const ADD_VAPESHOP_ERRORS = 'ADD_VAPESHOP_ERRORS';
export const REMOVE_VAPESHOP_ERRORS = 'REMOVE_VAPESHOP_ERRORS';
export const ADD_NEW_MARKER = 'ADD_NEW_MARKER';
export const REMOVE_NEW_MARKER = 'REMOVE_NEW_MARKER';